# Generated by Django 5.1.3 on 2024-12-03 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_location_location_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('country', 'Country'), ('state', 'State'), ('city', 'City')], default='city', max_length=20),
        ),
    ]
